### ISSUE TITLE
Laserio nodes crashing game "Ticking block entity"

### ISSUE THREAD

**Issue by MetalDom** [Direwolf20-MC/LaserIO#136]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.76

### Modpack & Version

All The Mods 7 To The Sky

### Do you have optifine installed?

No

### Describe the issue

I have a node connected to another node for power, it is also extracting items, and importing items and energy into another node. As soon as I placed an item card into the node inventory the game crashed, and now my single player world is corrupted. Exit Code: -1

### Steps to reproduce

1.  Open Minecraft
2. Use laser node on cobble gen, connected to ultimate mekanism energy cube, flux hammer, 
3. Use another laser node on another flux hammer transferring power and items from the previous hammer
4. Crash the game after item and energy cards are inserted and cry because u never made a backup of your world cus your dumb
5. Continue to launch your singleplayer world but continue to crash upon launch with an exit code: -1

### Expected behaviour

I expected items from my laserio to input into another flux hammer...

### Log files

at com.direwolf20.laserio.common.blockentities.LaserNodeBE$LaserEnergyStorage.receiveEnergy(LaserNodeBE.java:2387) ~[laserio-1.4.3.jar%23172!/:1.4.3] {re:classloading} 	at com.direwolf20.laserio.common.blockentities.LaserNodeBE.sendReceivedEnergy(LaserNodeBE.java:1156) ~[laserio-1.4.3.jar%23172!/:1.4.3] {re:classloading} 	at com.direwolf20.laserio.common.blockentities.LaserNodeBE.receiveEnergy(LaserNodeBE.java:1123) ~[laserio-1.4.3.jar%23172!/:1.4.3] {re:classloading} 	at com.direwolf20.laserio.common.blockentities.LaserNodeBE$LaserEnergyStorage.receiveEnergy(LaserNodeBE.java:2387) ~[laserio-1.4.3.jar%23172!/:1.4.3] {re:classloading} -- Block entity being ticked -- Details: 	Name: mekanism:ultimate_energy_cube // mekanism.common.tile.TileEntityEnergyCube 	Block: Block{mekanism:ultimate_energy_cube}[facing=up,fluid_logged=empty] 	Block location: World: (-16,67,12), Section: (at 0,3,12 in -1,4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511) 	Block: Block{mekanism:ultimate_energy_cube}[facing=up,fluid_logged=empty] 	Block location: World: (-16,67,12), Section: (at 0,3,12 in -1,4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511) Stacktrace: 	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:683) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.world.level.Level.redirect$zmk000$redirectTick(Level.java:1600) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A} 	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A} 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

### Additional information

Any information on how to maybe go into my files and correct the issue?

**Comment by Direwolf20-MC** [comment]
Resolved - thank you :)
